name: Main Actions

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CI: true

jobs:
  ios_build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: ['18']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test
    - name: Run lint
      run: yarn lint
    - name: Install iOS dependencies
      run: npx pod-install
    - name: Build iOS Project
      run: yarn build:ios
    # Example: Upload build artifact if build fails
    - name: Upload iOS build artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: ./artifacts

  android_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18']
        java-version: ['17']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test
    - name: Run lint
      run: yarn lint
    - name: Build Android APK
      run: yarn build:android
    # Example: Upload build artifact if build fails
    - name: Upload Android build artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: android-build-artifacts
        path: ./artifacts